### ISSUE TITLE
device-orientation

### ISSUE THREAD

**Issue by luboslives** [weblinc/media-match#19]
Does the script try to emulate device-orientation in IE 6-8? And if so, what exactly is it looking at?

I have a listener set for onresize which will change a background image, based on a matchMedia query looking for device-orientation. It seems to work as expected in IE 9 (and all other modern browsers), but it's completely whacky in the older Explorers.

**Comment by knightdr** [comment]
@luboslives 
Yes, it does. Orientation is determined by the greater of width and height eg. width > height = landscape. See media.match.js#L187 for a code example. A resize and orientation event are applied to the window to check for changes. This is how the native implementation works as well. If you test the orientation media query on a desktop, you'll see how the orientation will change on resize of the browser window.

I'd also recommend not using a window resize listener with matchMedia because matchMedia has it's own listener that's fired when the query result changes state from true to false and vice versa.

Try something like this...
```
<script type="text/javascript">
    window.matchMedia('(orientation: landscape)')
        .addListener(function(mql) {
            if (mql.matches) {
                // Media query does match
                alert('landscape');
            } else {
                // Media query does not match anymore
                alert('portrait');
            }
        });
</script>
```

**Comment by luboslives** [comment]
Thanks @knightdr, I reworked my code lately and now it's been working as expected in IE8. But i'll still have to look into replacing onresize with that matchMedia listener. Good to know!
